server:
  port: 8082

spring:
  main:
    web-application-type: servlet
  datasource:
    data: data.sql
    url: jdbc:mariadb://localhost:3306/registries
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: always
