INSERT INTO registries (id, name, surname, email)
VALUES (1, 'Mario', 'Rossi', 'mario.rossi@example.it'),
(2, 'Andrea', 'Neri', 'andrea.neri@example.it'),
(3, 'Lucia', 'Verdi', 'lucia.verdi@example.it'),
(4, 'Sara', 'Bianchi', 'sara.bianchi@example.it'),
(5, 'Gianni', 'Morandi', 'gianni.morandi@example.it'),
(6, 'Olga', 'Streisand', 'olga.streisand@example.it'),
(7, 'Vincenzo', 'valenti', 'vincenzo.valenti@example.it'),
(8, 'Stefano', 'Grossi', 'stefano.grossi@example.it'),
(9, 'Milena', 'Fabbri', 'milena.fabbri@example.it'),
(10, 'Gianluca', 'Belli', 'gianluca.belli@example.it'),
(11, 'Ilaria', 'Terni', 'ilaria.terni@example.it'),
(12, 'Antonio', 'Esposito', 'antonio.esposito@example.it'),
(13, 'Tiziana', 'DeMarco', 'tiziana.demarco@example.it'),
(14, 'Linda', 'Rossi', 'linda.rossi@example.it'),
(15, 'Francesco', 'Piatti', 'francesco.piatti@example.it'),
(16, 'Herr', 'Schmidt', 'herr.schmidt@example.it'),
(17, 'Juan', 'Carlos', 'juan.carlos@example.it'),
(18, 'Bonnie', 'Fritz', 'bonnie.fritz@example.it'),
(19, 'Mark', 'Doe', 'mark.doe@example.it'),
(20, 'Jane', 'Doe', 'jane.doe@example.it'),
(21, 'Jill', 'Valentine', 'jill.valentine@example.it');

