CREATE DATABASE IF NOT EXISTS registries;

USE registries;

DROP TABLE registries;

CREATE TABLE registries (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	surname VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	address VARCHAR(100),
	location VARCHAR(100),
	city VARCHAR(100),
	province VARCHAR(100),
	notes VARCHAR(1000)
);